language: python

jobs:
  include:
    - stage: duplicate
      name: One
      env: FOO=one
      script: &foo
        - echo $FOO
        - echo $BAR
    - stage: duplicate
      name: Two
      env: FOO=two
      script: *foo

env:
  global:
    - BAR=baz
