language: python

jobs:
  include:
    - stage: duplicate
      name: One
      env: FOO=one
      script: &foo
        - echo $FOO
    - stage: duplicate
      name: Two
      env: FOO=two
      script: *foo
